### PR TITLE
Dev

### LINKED ISSUE #5: TUI Stackoverflow bug
If a TUI method receives an input of an invalid data type, it breaks the "eingabe" object and causes a stackoverflow error.

### PR DESCRIPTION
**Pull request by LeonWilzer**
Two methods for clearing the console and a shorthand for printing to the console.

fixes #5

### CODE REVIEW

**Review by lukaslangrock — APPROVED** [review]
looking good 👍

**Comment by LeonWilzer** [comment]
Did you take a look at the conflicts below, @lukaslangrock ?

**Comment by lukaslangrock** [comment]
Sorry, I thought you would resolve them.
I'll fix them now.

**Comment by lukaslangrock** [comment]
hmm most of them were just about the `package RPG;` line, I wonder why GitHub couldn't merge automatically.

**Comment by LeonWilzer** [comment]
Merge

**Pull request merged**
